---
name: Common Setup Steps

inputs: {}

runs:
  using: composite
  steps:
  - name: Setup mise
    uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
    with:
      version: v2026.1.7
