---
name: Common Setup Steps

inputs: {}

runs:
  using: composite
  steps:
  - name: Setup mise
    uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
    with:
      version: v2026.1.7
