# Please Do Not use "latest" until lock files are implemented
# https://github.com/jdx/mise/discussions/6578
# https://github.com/jdx/mise/pull/6231
[tools]
go = "1.26.5"
golangci-lint = "2.5.0"
terraform = "1.15.8"

# go backend is experimental
[settings]
experimental = true
