on:
  push:
    branches:
      - main # running from the default branch makes the go build cache available to PRs.

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      native: true
      snapshot: true
