name: Release Please

# 1. Run release-please on every push to main
# 2. Trigger publishing only when a new tag is pushed
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          # GoReleaser is responsible for creating the GitHub release and uploading artifacts.
          skip-github-release: true
    outputs:
      releases: ${{ toJson(steps.release.outputs) }}
      paths_released: ${{ steps.release.outputs.paths_released }}

  release:
    needs: release-please
    if: ${{ contains(needs.release-please.outputs.paths_released, '.') }}
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/release.yml
    with:
      git-tag: ${{ fromJson(needs.release-please.outputs.releases).tag_name }}
