name: Release Please

# 1. Run release-please on every push to main
# 2. When release-please creates a release, trigger the release job to publish via GoReleaser
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          # Release Please creates the release, goreleaser populates it with artifacts
          release-type: go
    outputs:
      releases: ${{ toJson(steps.release.outputs) }}
      paths_released: ${{ steps.release.outputs.paths_released }}

  release:
    needs: release-please
    if: ${{ contains(needs.release-please.outputs.paths_released, '.') }}
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/release.yml
    with:
      git-tag: ${{ fromJson(needs.release-please.outputs.releases).tag_name }}
